# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-23 15:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sat_year', models.CharField(max_length=200)),
                ('apply_univ', models.CharField(max_length=20)),
                ('apply_faculty', models.CharField(max_length=20)),
                ('apply_way', models.CharField(max_length=20)),
                ('origin_school', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Jungsi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sat_kor', models.IntegerField()),
                ('sat_math', models.IntegerField()),
                ('sat_gpa_eng', models.IntegerField()),
                ('sat_gpa_history', models.IntegerField()),
                ('sat_choice1', models.IntegerField()),
                ('sat_choice2', models.IntegerField()),
                ('sat_language', models.IntegerField()),
                ('result', models.CharField(choices=[('p', 'Progress'), ('r', 'Rejected'), ('a', 'Accepted')], default='Progress', max_length=1)),
                ('apply', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ipsi.Apply')),
            ],
        ),
        migrations.CreateModel(
            name='Susi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gpa', models.IntegerField()),
                ('non_subject', models.TextField()),
                ('subject', models.TextField()),
                ('apply', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ipsi.Apply')),
            ],
        ),
    ]
