# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-26 06:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipsi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jungsi',
            name='result',
        ),
        migrations.AddField(
            model_name='susi',
            name='interview',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='susi',
            name='result',
            field=models.CharField(choices=[('p', 'Progress'), ('r', 'Rejected'), ('a', 'Accepted')], default='Progress', max_length=1),
        ),
    ]
