# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-28 15:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipsi', '0002_auto_20170626_1521'),
    ]

    operations = [
        migrations.AddField(
            model_name='apply',
            name='options',
            field=models.CharField(choices=[('s', '수시'), ('j', '정시')], default='정시', max_length=1),
        ),
    ]
